name: cheon
description: A Smart Study Planner.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ################################ UI PACKAGES #################################

  # Icons from https://fontawesome.com
  font_awesome_flutter: ^8.10.0

  # Animated loading indicators
  flutter_spinkit: ^4.1.2+1

  # Creates a dashed line border around a provided widget
  dotted_border: ^1.0.6

  # Places a label at the top of scrolling lists
  sticky_headers: ^0.1.8+1

  # Renders text based on the markdown text formatting standard
  flutter_markdown: ^0.5.0

  # Renders a Scalable Vector Graphic image
  flutter_svg: ^0.18.1

  # Official animations package providing Material Design transitions
  animations: ^1.1.2

  # Render html
  flutter_html: ^1.0.2

  ########################## DATA PERSISTENCE PACKAGES #########################

  # A super fast key value store
  hive: ^1.4.4+1

  # Adds SQLite support with Data Access Objects and streams
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.2.0

  # Supplies the app with the directory location for storing files
  path_provider: ^1.6.22

  ############################### OTHER PACKAGES ###############################

  # Officially endorsed state management library with O(1) access time from
  # anywhere in the widget tree
  provider: ^4.3.2+2

  # Opens urls in the phone browser
  url_launcher: ^5.7.2

  # Supplies the app version details e.g. build name/number
  package_info: ^0.4.3

  # Shares in app content using respective system sharing APIs
  share: ^0.6.5+4

  # Allows the app to be opened to a specific page/feature from the app launcher
  quick_actions: ^0.4.0+10

  # Inversion of control container based dependency injection using a map
  # Supports constructor injection.
  kiwi: ^2.1.1

  # Creates fuzzy timestamps from DateTime objects e.g. 5 minutes ago
  timeago: ^2.0.28

  # Annotations for classes that utilise code gen from json_serializable
  json_annotation: ^3.1.0

  # ReaxtiveX Dart. Provides extra features to Dart's streams
  rxdart: ^0.24.1

  # Uses platform APIs to send push notifications
  flutter_local_notifications: ^1.4.4+4

  # Generates and parses Universally unique identifiers
  uuid: ^2.2.2

  # Required package for the Firebase platform
  firebase_core: ^0.5.0+1
  # Analytics for the Firebase platform
  firebase_analytics: ^6.0.2
  # Crash monitoring
  firebase_crashlytics: ^0.2.1+1

  # Retreives events from the default device calendar
  device_calendar: ^3.1.0

  # Enables object comparison without overriding == and hashCode
  equatable: ^1.2.5

  # In app feedback by wiredash.io
  wiredash: ^0.3.0

  # Drag to hide keyboard on IOS
  flutter_interactive_keyboard: ^0.1.3

  # Shows a rating popup after certain conditions are met
  rate_my_app: ^0.7.2

  # Sorts imports!
  import_sorter: ^4.2.2

  # In-App Review pop up
  in_app_review: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Home screen icon generator
  flutter_launcher_icons: ^0.8.1

  # Splash screen generator
  flutter_native_splash: ^0.1.9

  # Mocks classes for testing purposes
  mockito: ^4.1.3

  ############################## Code Generation ###############################
  # Run:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # Or run:
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  # To execute the code generation process either once or for every file change
  # with the watch command

  # Official code generation package for Dart
  build_runner: ^1.10.2

  # Constructor injection code generator for kiwi
  kiwi_generator: ^2.1.1

  # Dart sqlite table to raw sql code generator for moor
  moor_generator: ^3.4.0

  # Uses code generation to generate serialization functions to convert objects
  # to and from JSON
  json_serializable: ^3.5.0

dependency_overrides:
  flutter_svg: ^0.18.1
  # # Removes nullsafety
  # characters: 1.0.0
  # collection: 1.14.13
  # matcher: 0.12.9
  # meta: 1.2.2
  # typed_data: 1.2.0
  # vector_math: 2.0.8

# part of the flutter_launcher_icons package
# run flutter pub run flutter_launcher_icons:main to update icons
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logo/logo.png"
  # Cannot contain transparency for IOS
  image_path_ios: "assets/logo/logo_filled.jpg"

# Settings for the flutter_native_splash package
# run flutter pub run flutter_native_splash:create to update splash screen
flutter_native_splash:
  image: assets/icons/logo_filled.jpg
  color: "4caf50"
  android: false

# run flutter pub run import_sorter:main to sort imports
import_sorter:
  ignored_files:
    - \/*.g.dart/

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/logo/
    - assets/images/

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Medium.ttf
    - family: CheonIcons
      fonts:
        - asset: fonts/CheonIcons.ttf
