name: cheon
description: A Smart Study Planner.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ################################ UI PACKAGES #################################

  # Icons from https://fontawesome.com
  font_awesome_flutter: ^8.8.1

  # Animated loading indicators
  flutter_spinkit: ^4.1.2+1

  # Creates a dashed line border around a provided widget
  dotted_border: ^1.0.5

  # Places a label at the top of scrolling lists
  sticky_headers: ^0.1.8+1

  # Renders text based on the markdown text formatting standard
  flutter_markdown: ^0.4.1

  # Renders a Scalable Vector Graphic image
  flutter_svg: ^0.18.0

  # Official animations package providing Material Design transitions
  animations: ^1.1.0

  # Customisable Material & Cupertino date picker
  flutter_rounded_date_picker: ^1.0.4

  ########################## DATA PERSISTENCE PACKAGES #########################

  # A super fast key value store
  hive: ^1.4.1+1

  # Adds SQLite support with Data Access Objects and streams
  # TODO address breaking changes introduced in 3.1.0
  moor: ^3.1.0
  # moor_flutter: ^2.1.1
  # https://github.com/simolus3/moor/issues/446
  moor_ffi: 0.5.0
  # update moor once this issue is fixed
  # https://github.com/simolus3/moor/issues/581

  # Supplies the app with the directory location for storing files
  path_provider: ^1.6.10

  ############################### OTHER PACKAGES ###############################

  # Officially endorsed state management library with O(1) access time from
  # anywhere in the widget tree
  provider: ^4.1.3

  # Opens urls in the phone browser
  url_launcher: ^5.4.10

  # Supplies the app version details e.g. build name/number
  package_info: ^0.4.1

  # Shares in app content using respective system sharing APIs
  share: ^0.6.4+3

  # Allows the app to be opened to a specific page/feature from the app launcher
  quick_actions: ^0.4.0+6

  # Inversion of control container based dependency injection using a map
  # Supports constructor injection.
  kiwi: ^0.3.3

  # Creates fuzzy timestamps from DateTime objects e.g. 5 minutes ago
  timeago: ^2.0.26

  # Annotations for classes that utilise code gen from json_serializable
  json_annotation: ^3.0.1

  # ReaxtiveX Dart. Provides extra features to Dart's streams
  rxdart: ^0.24.1

  # Uses platform APIs to send push notifications
  flutter_local_notifications: ^1.4.4+1

  # Generates and parses Universally unique identifiers
  uuid: ^2.1.0

  # Required package for the Firebase platform
  firebase_core: ^0.4.5
  # Analytics for the Firebase platform
  firebase_analytics: ^5.0.15
  # Custom messages to increase engagement
  firebase_in_app_messaging: ^0.1.2
  # Remotely triggered push notifications
  # firebase_messaging: ^6.0.12
  # Crash monitoring
  firebase_crashlytics: ^0.1.3+3

  # Retreives events from the default device calendar
  device_calendar: ^3.1.0

  # Enables object comparison without overriding == and hashCode
  equatable: ^1.2.0

  # In app feedback by wiredash.io
  wiredash: ^0.2.0

  # Drag to hide keyboard on IOS
  flutter_interactive_keyboard: ^0.1.3

  # Shows a rating popup after certain conditions are met
  rate_my_app: ^0.6.1+4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # Home screen icon generator
  flutter_launcher_icons: ^0.7.5

  # Splash screen generator
  flutter_native_splash: ^0.1.9

  # Mocks classes for testing purposes
  mockito: ^4.1.1

  ############################## Code Generation ###############################
  # Run:
  # flutter packages pub run build_runner build
  # Or run:
  # flutter packages pub run build_runner watch
  # To execute the code generation process either once or for every file change
  # with the watch command

  # Official code generation package for Dart
  build_runner: ^1.10.0

  # Constructor injection code generator for kiwi
  kiwi_generator: ^0.5.2

  # Dart sqlite table to raw sql code generator for moor
  moor_generator: ^3.1.0

  # Uses code generation to generate serialization functions to convert objects
  # to and from JSON
  json_serializable: ^3.3.0

dependency_overrides:
  xml: ^4.1.0

# part of the flutter_launcher_icons package
# run flutter pub run flutter_launcher_icons:main to update icons
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/logo/logo.png"
  # Cannot contain transparency for IOS
  image_path_ios: "assets/logo/logo_filled.jpg"

# Settings for the flutter_native_splash package
# run flutter pub pub run flutter_native_splash:create to update splash screen
flutter_native_splash:
  image: assets/icons/logo_filled.jpg
  color: "4caf50"
  android: false

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/logo/
    - assets/images/

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Medium.ttf
    - family: CheonIcons
      fonts:
        - asset: fonts/CheonIcons.ttf
