name: Flutter Build
on: [push, pull_request]
jobs:
  build_ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b beta _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
      - run: flutter build ios --no-codesign
      - run: git diff --exit-code
  build_android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b beta _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
      - run: flutter build appbundle --release --flavor prod 
      - run: git diff --exit-code
