name: Quality Assurance
on: [push, pull_request]
jobs:
  main:
    name: Quality Assurance on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter pub get
      #         Runs the formatter
      # - run: flutter format lib/* --set-exit-if-changed
      # Run code generation and fail the build if any files change as a result
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      # - run: flutter pub run flutter_native_splash:create
      - run: flutter pub run flutter_launcher_icons:main
      - run: flutter pub run import_sorter:main --exit-if-changed
      - run: git diff --exit-code
      # Runs standard tests
      - run: flutter test --no-pub --coverage
      # Uploads coverage to Codecov if running windows
      - uses: codecov/codecov-action@v1.0.7
        if: matrix.os == 'windows-latest'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
